import {
  SiGithub,
  SiReact,
  SiAngular,
  SiPhp,
  SiExpress,
  SiNodedotjs,
  SiLaravel,
  SiNextdotjs,
  SiTypescript,
  SiRedux,
  SiTailwindcss,
  SiWordpress,
  SiGit,
  SiDocker,
  SiMysql,
  SiPostgresql,
  SiFigma,
} from '@icons-pack/react-simple-icons';

export const techSkillIcons = [
  { name: 'React', icon: SiReact },
  { name: 'Next.js', icon: SiNextdotjs },
  { name: 'Angular', icon: SiAngular, color: '#DD0031' },
  { name: 'TypeScript', icon: SiTypescript },
  { name: 'Redux', icon: SiRedux },
  { name: 'Tailwind', icon: SiTailwindcss },
  { name: 'Express.js', icon: SiExpress },
  { name: 'Node.js', icon: SiNodedotjs },
  { name: 'Laravel', icon: SiLaravel },
  { name: 'PHP', icon: SiPhp },
  { name: 'WordPress', icon: SiWordpress },
  { name: 'MySQL', icon: SiMysql },
  { name: 'PostgreSQL', icon: SiPostgresql },
  { name: 'Docker', icon: SiDocker },
  { name: 'Git', icon: SiGit },
  { name: 'GitHub', icon: SiGithub },
  { name: 'Figma', icon: SiFigma, color: '#000' },
];
