import type { Metadata } from 'next';
import './globals.css';
import { azaret_mono, inter } from '@/lib/fonts';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';

// static metadata
export const metadata: Metadata = {
  title: {
    default: 'Portfolio',
    template: '%s | Portfolio', // Prefix child comp metadata. %s is var for e.g. Blog. Look into Blog page
    absolute: '', // Also for child comp, will override template prefixes
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} ${azaret_mono.variable} antialiased`}>
        <Header />
        <main className="mx-auto my-12 max-w-6xl">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
